### PR TITLE
Add GitHub activity

### PR DESCRIPTION
**Pull request by danfowler**
Resolving #272

### CODE REVIEW

**Comment by danfowler** [comment]
It would be nice to merge this after some tweaks to githubActivity.js (okfn/githubActivity.js#3)

**Comment by rgrp** [comment]
https://github.com/okfn/githubActivity.js/pull/3 is done.

**Comment by mchelen** [comment]
Tested locally and it looks good. The only thing is maybe try to keep the "Recent Project Activity" title directly before the embed, and move the GH buttons either above the title or below the activity stream.

**Comment by danfowler** [comment]
Thanks for the suggestions, @mchelen.  I made the changes and am now merging.

**Pull request merged**
