### PR TITLE
add data wrangling guest post - datapak gem - working with tabular data packages w/ ruby and sqlite

### PR DESCRIPTION
**Pull request by geraldb**
Hello,
   Thanks for the great tabular data package format. I've coded and published a little library in Ruby that lets you work with tabular data packages with Ruby ActiceRecord models (ORM wrapper) and, thus, your SQL database of choice (by default the library will use an in-memory SQLite database). It would be great to get the post about the datapak gem (library) posted on the Data Wrangling Blog. Feel free to change or edit as needed. Cheers.
PS: I'm the author of a previous guest post (last year in 2014) about the football.db and open data for the World Cup in Brazil.

### CODE REVIEW

**Comment by rgrp** [comment]
@danfowler are you happy to review and merge (and then announce to okfn-labs list)?

**Comment by danfowler** [comment]
Yup. Currently in transit now, so will come  sometime after the next few
hours.

**Comment by geraldb** [comment]
Thanks. Fantastic. Take your time. No rush. Cheers.

**Comment by danfowler** [comment]
Great post! I will merge and make a few stylistic edits. @geraldb would you mind also [adding yourself as a user](http://okfnlabs.org/members/signup/)?

**Comment by geraldb** [comment]
@danfowler  Great thanks. Will try to get the user page added later today. Cheers.

**Comment by danfowler** [comment]
@geraldb cool. I made some edits mainly around two points: 1. I jumped straight into your contribution rather than reviewing the basics of tabular data packages, and 2. Some tweaks to the examples to make them easier to follow (for me) in irb.

Before I merge, could you just verify that it still accords with your fundamental idea about the post: https://github.com/danfowler/okfn.github.com/commit/82a4328ebffd2e80e25e35a430868a6684057673#diff-7c19899ac3d3c5781bdae6d66f919523

**Comment by geraldb** [comment]
@danfowler  Sure. No worries. Looks good. Thanks. Cheers.

**Comment by geraldb** [comment]
@danfowler   I added the user/member page - see  members/_posts/2015-04-28-geraldb.html  GitHub (automagically) updated this pull request. Let me know if the new user/member works for you. Cheers.

**Comment by danfowler** [comment]
Looks good.

**Comment by rgrp** [comment]
@danfowler are we good to merge and get this announced to the list?

**Comment by danfowler** [comment]
Just about. It's a bit late here, so will merge and announce tomorrow morning.

**Comment by geraldb** [comment]
Fantastic. Thanks. Will try to send in another guest post in the upcoming weeks about using wikiscript to get structured data from tables and infoboxes in Wikipedia pages. Cheers. Have a great weekend. Keep it up.

**Comment by danfowler** [comment]
:+1:

**Pull request merged**
