### PR TITLE
post/goodtables

### PR DESCRIPTION
**Pull request by pwalsh**
* adds new post for good tables web service
* makes changes to previous post to reflect updated library name
* add support for jekyll redirects

### CODE REVIEW

**Comment by danfowler** [comment]
Cool! Thanks @pwalsh.  The build failed because (a) you introduced a new (whitelisted) plugin and (b) the Travis CI setup wasn't completely aligned with the GitHub Pages build process. I made some tweaks in a [separate branch](https://github.com/okfn/okfn.github.com/pull/309) that allows Travis CI to build properly again.

I do think it's a good idea to start using this plugin, but I just want to make sure the other contributors @mchelen @rgrp @loleg are happy with altering the build step (best accomplished by installing Bundler and using "bundle exec jekyll build" instead of just "jekyll build').  

Of course, we could just merge your new posts without the plugin (and 404'ing on your old post url), and think about new plugins later.

**Comment by pwalsh** [comment]
Hi, I only added it because it is a supported plugin on github pages, meaning it doesn't require a build step before pushing. Is the labs blog built before pushing?

**Comment by danfowler** [comment]
I understand, and I think the plugin is a good addition.  The site is built on GitHub, so you're right, no build step.  What I suggested would only apply to local testing.

**Comment by rgrp** [comment]
@danfowler hope ok that i merged (your comment only just appeared for me!).

**Comment by danfowler** [comment]
@rgrp :+1:

**Pull request merged**
