### PR TITLE
All changes relate to issue 424,merging project maintainers and contributors

### PR DESCRIPTION
**Pull request by davbre**
See https://github.com/okfn/okfn.github.com/issues/424#issuecomment-219282827

### CODE REVIEW

**Comment by danfowler** [comment]
Cool! 👀

**Comment by danfowler** [comment]
@davbre We need to also remove the now empty maintainers column in the projects.csv file, no?

**Comment by davbre** [comment]
@danfowler - at some stage, yes. It still being there has no effect though.
I thought leaving it there for now would make it easier to see what changes
were made to the projects.csv file (I.e. when you're looking at a diff).
I'll remove it now if you like or in a subsequent pull request.

**Comment by danfowler** [comment]
No worries, just checking.  Merging.

**Pull request merged**
