### PR TITLE
Add a new member

### PR DESCRIPTION
**Pull request by jgkim**
Added myself as a new labs member.

### CODE REVIEW

**Comment by rgrp** [comment]
Welcome!

**Comment by jgkim** [comment]
@rgrp Thank you! How can I join the Github organization of the Open Knowledge (https://github.com/okfn)?

**Comment by rgrp** [comment]
@jgkim you don't automatically join the okfn org on github - rather you join specific repos that you are contributing to. Are there specific projects - http://okfnlabs.org/projects/ that you plan to work on?

**Comment by jgkim** [comment]
@rgrp I'm interested in `DataPortals.org`, and will look for others.

**Comment by rgrp** [comment]
@jgkim that's great - dataportals.org definitely needs your assistance :-) Please take a look at the issues https://github.com/okfn/dataportals.org/issues and start commenting. The usual process is to start contributing and then you become a committer.

**Comment by rgrp** [comment]
@jgkim you are doing great work on the Open Data Handbook. One other area where contribution is really welcome is the Core Datasets project: http://okfnlabs.org/blog/2015/01/03/data-curators-wanted-for-core-datasets.html and http://data.okfn.org/doc/core-data-curators

**Pull request merged**
