### PR TITLE
Remove Google Calendar

### PR DESCRIPTION
**Pull request by avdata99**
Related to #548 

If hangouts for Labs are not happening any more we can drop calendar from this site.

### CODE REVIEW

**Comment by avdata99** [comment]
We probably also need to re define how we build this site #550

**Comment by augusto-herrmann** [comment]
I'm not sure if whether or not the hangouts for Labs are still happening. Maybe not. I, at least, haven't participated in one for years.

**Review by augusto-herrmann — APPROVED** [review]
I think it's probably ok to remove it.

**Review by amercader — APPROVED** [review]

**Comment by augusto-herrmann** [comment]
Thanks, @avdata99!

**Pull request merged**
