### PR TITLE
Various changes to the projects page

### PR DESCRIPTION
**Pull request by davbre**

### CODE REVIEW

**Comment by rgrp** [comment]
@davbre this is good - though ironically i meant the *old* openeconomics project (pre the WG) which was more technical in nature ;-). See:

http://web.archive.org/web/20100401182854/http://www.openeconomics.net/

Should we merge and update or do you want to update now - or close this and we do a new one?

**Comment by davbre** [comment]
@rgrp - I've just updated the PR. It has also merged "stage" and "maturity_status" into "stage".

**Comment by rgrp** [comment]
@davbre when you say merged can I check we discarded "old" stage entirely and just went with `maturity_status`?

**Comment by davbre** [comment]
@rgrp in the google docs spreadsheet you added the label "stage (new) (was
maturity_status)" to the column. So, I renamed `maturity_status` to `stage`
(i.e. there is now no `maturity_status` column...everything is in `stage`).
Ok with you?

**Comment by davbre** [comment]
@rgrp this last commit contains a few fixes. I broke portions of some pages - the "related posts" section on blog posts, the "projects" section on members pages and some stuff relating to badges. I gave it a right old stomping...sorry about that :)

**Comment by rgrp** [comment]
@davbre ok great. BTW what has happened to *new* featured column (the old one we are deleting i know)? Have we not yet merged that in?

**Comment by davbre** [comment]
@rgrp - I obviously misunderstood... I was thinking along these lines...

The original default filter displayed the "featured" projects and the new default filter should display the "priority" projects. So, the "featured" projects are not really "featured" as such, because they're not the default. So I thought it odd that this filter be included. Do you see what I mean?

In any case, it is very easy to re-instate this filter as I have not removed the metadata from the projects.csv file (the column was simply re-named `archived_featured`).

Would you like to re-instate it? If so, no problem...it's a quick fix.

**Comment by rgrp** [comment]
@davbre so is the `archived_featured` the *new* featured column from the google doc? If so, yes let's please reinstate that and the features default filter.

Also should we squash some of these commits down? Looking forward to getting this in :-)

Note: Any changes to the /projects/ page will follow later on discussion in #422.

**Comment by davbre** [comment]
@rgrp - yes, `archived_featured` was the _new_ featured column. I have renamed it and it now reinstated as a filter in the projects page. I've also squashed the commits into one.

**Pull request merged**
