### PR TITLE
updates pandas notebook

### PR DESCRIPTION
**Pull request by lwinfree**
As part of updating our documentation to docs.frictionlessdata.io, I wanted to update this jupyter notebook as some of the code had deprecated over time.  I also added some more comments and some extended examples of using Pandas.

### CODE REVIEW

**Comment by todrobbins** [comment]
looks good to me! 🎉

**Comment by augusto-herrmann** [comment]
@lwinfree and @todrobbins, this way of using `datapackage.push_datapackage` has been deprecated and no longer works with current versions. See [tableschema-pandas-py#33](https://github.com/frictionlessdata/tableschema-pandas-py/issues/33).

@roll has [recently updated the README](https://github.com/frictionlessdata/tableschema-pandas-py/commit/d7184bc1c4adbd34e868c44ee6138763fb42d413) with a working example you can use.

**Comment by todrobbins** [comment]
Ah, thanks for the heads up @augusto-herrmann!

**Comment by augusto-herrmann** [comment]
I have created [a new PR](https://github.com/okfn/okfn.github.com/pull/543) to update the notebook again.

**Comment by lwinfree** [comment]
Thank you @augusto-herrmann!! I really appreciate the update & new PR :-)

**Comment by augusto-herrmann** [comment]
You are welcome. Glad to be of help.

BTW, are these notebooks being used on the okfnlabs.org site anywhere?

Does [PR#544](https://github.com/okfn/okfn.github.com/pull/544) even make sense?

**Comment by lwinfree** [comment]
Hi @augusto-herrmann! The pandas notebook is linked in a post on okfnlabs.org, but I was mainly updating it to add to our new documentation site: https://github.com/frictionlessdata/docs

Thanks for bringing my attention to PR#544 - that notebook looks great! It would be useful to add to the new docs site. If it isn't too much trouble, do you think you could open a PR there? It would go in the 'docs/tutorials/datapackage-tutorials' file path. If that is too complicated, I can merge your PR here and add the notebook to the docs myself. Let me know what you think :-)
 And thanks again!

**Comment by augusto-herrmann** [comment]
Good idea, @lwinfree. It's [done](https://github.com/frictionlessdata/docs/pull/11)!

**Comment by lwinfree** [comment]
Woo thanks @augusto-herrmann!!

**Pull request merged**
