### PR TITLE
adding myself as a member

### PR DESCRIPTION
**Pull request by augusto-herrmann**
as [suggested](https://github.com/okfn/publicbodies/issues/65#issuecomment-159985307) by @danfowler

### CODE REVIEW

**Comment by todrobbins** [comment]
Yay! 🎉

**Comment by danfowler** [comment]
Bem-vindo!

**Comment by augusto-herrmann** [comment]
Thanks!
BTW, I've put my membership date as the earliest date I could find documented (I think it was actually a little before that, just couldn't find the documented evidence) of a contribution I made to an Open Knowledge project. I took as an example @rgrp's and @pudo's profiles, both of which predate the okfnlabs website. Not sure if that was correct or if I should have put the date of today instead.

**Comment by danfowler** [comment]
@augusto-herrmann makes sense to me :+1:

**Comment by todrobbins** [comment]
Looks great.

**Pull request merged**
