### PR TITLE
Fix 2030 Watch in projects csv

### PR DESCRIPTION
**Pull request by svanderwaal**
2030 Watch had 20 columns instead of 22. 
Added two commas to make values most likely align with intended values.

### CODE REVIEW

**Comment by rufuspollock** [comment]
Thanks @svanderwaal 👍 😄 🏂

**Comment by mattfullerton** [comment]
Thanks also from me :smile: 

I must say this CSV file approach is a huge hurdle for adding a new project. Any objections to moving to a folder of JSONs? Jekyll supports that quite well.

**Comment by davbre** [comment]
@mattfullerton - are you talking about having a single file for each project or one JSON file to replace the CSV file? Although not ideal, one of the advantages with the single CSV file is that it's easier to edit all projects at once (i.e. by opening in LibreOffice, Excel etc).

**Comment by mattfullerton** [comment]
@davbre I'm talking about one file per project. If we changed the schema I think a quick script to reformat would outweigh the time people spend dealing with this format. I personally wouldn't trust Libreoffice/Excel to edit this file, maybe I'm just paranoid.

What might help though (sticking with CSV) is a first line in the file (that gets ignored) that explains valid entries.

**Comment by davbre** [comment]
@mattfullerton - we could perhaps add a dummy project with all of necessary fields filled out? Or are you talking about more explicit instructions embedded within the CSV?

As a side note - prior to using the CSV file, each project had its own file, with its frontmatter declared at the top in the usual way. The problem with this was that as projects were added over the years, the attributes being declared differed quite a bit. This made it tricky to apply consistency across the projects, and also when scripting templates because you're never sure which attributes are present across which projects. Last year we cleaned up the project metadata and, for me, using the CSV file made things significantly easier. What I liked was...
    
- it provided a good overview of all projects
- multiple projects can be edited, all at once
- attributes could be added/deleted across all projects by adding/deleting columns
- the sort order of the projects could be easily changed (this was achieved previously by using the YEAR-MONTH-DAY-title filename convention which was not ideal)

In my case I used google docs and LibreOffice and have no complaints, as I can do a diff after editing to make sure the formatting hasn't been screwed up. I take your point that when editing a single project it's less pleasant than editing a single file (if using just a text editor at least), and if people would prefer to go back to single files then that's fine with me, but I think we'd lose the benefits outlined above (although this could be mitigated with some scripts I guess).

**Comment by danfowler** [comment]
A clear use case for a CSV validator as a Jekyll plugin (if only GitHub Pages supported plugins):

https://github.com/theodi/csvlint.rb

I think keeping as CSV is good enough for the time being.

**Pull request merged**
