### PR TITLE
New Post: Intro to stats with data packages and Gonum

### PR DESCRIPTION
**Pull request by danielfireman**

### CODE REVIEW

**Comment by todrobbins** [comment]
anyone else want to take a look before merging? @okfn/oki-labs-community

**Comment by rufuspollock** [comment]
@todrobbins go for it!

**Comment by todrobbins** [comment]
Thanks for the contribution, @danielfireman! 🎉

**Comment by danielfireman** [comment]
@todrobbins I believe there was a typo or something which broke the post rendering in the [OKF labs blog](https://okfnlabs.org/blog/2019/08/01/intro-statistics-datapackage-gonum.html). The screenshot below can help to identify. Could you please help?

Screenshot from 2019-08-01 15-20-37

**Comment by todrobbins** [comment]
Whoops! I'll look into!

**Comment by danielfireman** [comment]
Sent https://github.com/okfn/okfn.github.com/pull/539

**Pull request merged**
