### PR TITLE
Create 2015-10-30-davbre.html

### PR DESCRIPTION
**Pull request by davbre**

### CODE REVIEW

**Comment by danfowler** [comment]
@davbre welcome!

**Comment by davbre** [comment]
Thanks!

**Comment by danfowler** [comment]
@davbre how did you find out about Labs?

**Comment by davbre** [comment]
@danfowler when I started working on [this project](https://github.com/davbre/mira) of mine, I was searching for some sort of standard metadata format for tables of data. I found Tabular Data Packages, which stems from Labs. As it turns out, it was exactly what I needed :)

**Comment by danfowler** [comment]
@davbre really great work. If you're looking for help building it, we have a Labs discussion forum here where you can introduce your project: https://discuss.okfn.org/c/open-knowledge-labs

You could also submit it for inclusion into our newsletter: http://okfnlabs.org/newsletter/.  It's great to see projects like yours building on and using the Tabular Data Package format.

**Comment by davbre** [comment]
@danfowler thanks! I'll do that when I get a chance over the next few days.

**Pull request merged**
