### PR TITLE
Reduce project image sizes

### PR DESCRIPTION
**Pull request by mchelen**
This is an attempt to address https://github.com/okfn/okfn.github.com/issues/164

 - The Gruntfile contains a custom task `grunt projectimg` which reads the YAML frontmatter in all the `projects/_posts/` files and saves the output in JSON format as `_data/projectimages.json`
 - The JSON file is read by `grunt curl` to download all the images to `img/projects/`
 - The images are compressed using `grunt imagemin`

The files are named using the project slugs, and `projects/index.md` and `_layouts/project.html` have been updated to use the new files when appropriate.

The advantage to this is that users only have to supply a URL, as opposed to uploading files. The downside is that someone has to periodically run the Grunt task before updating the website.

Let me know if this seems like a reasonable approach, and I can streamline the workflow to run all the commands in batch and along with the Jekyll build command.

Todo:
- [x] include all tasks in `grunt dist`
- [x] document in readme
- [x] cleanup `package.json` author & license fields

### CODE REVIEW

**Comment by loleg** [comment]
My suggestion would be to configure folders, which are traversed for image files (and [.url files](http://www.fmtz.com/formats/url-file-format/article)? why is there no better standard..) that are automatically downscaled. This is coupled with [recommendations](www.smashingmagazine.com/2014/02/03/one-solution-to-responsive-images/) on CSS/JavaScript implementation and an update to the site themes. I like where [BBC-News/Imager.js](https://github.com/BBC-News/Imager.js/) is going.

**Comment by loleg** [comment]
@mchelen it would be great if you could update your branch so we can merge the PR - thanks again.

**Comment by mchelen** [comment]
@loleg Ok sure, I fixed the merge conflicts. What you describe in https://github.com/okfn/okfn.github.com/pull/252#issuecomment-68715098 is pretty much what is happening here. The only additional step is that we first need to pull the remote images and save them locally.

**Comment by loleg** [comment]
@mchelen I've tested the build and saw no issues and would love to close the PR.. last 2 questions: the images are being reduced to something like 1000px across. However the width they are used at in the page is 470px. I don't see Retina support in the CSS, so why the res? Also, is there any reason the filenames do not have an extension?

**Comment by mchelen** [comment]
@loleg The code so far does not resize, it only optimizes. I was thinking about leaving resize for another PR, once the framework is in place.
The filenames have no extensions because when I was looking through the external file URLS some did not have extensions, and I didn't want to write more code to handle the different cases. If needed I could pull the extension from URLs when it is available, but either way shouldn't make a difference for the web browser.

**Comment by danfowler** [comment]
I really like this code.  It's the best solution so far to a very real issue.  But one thing that has held me back from merging until now is that, by its nature, it would automatically add a set of images directly to the repo.  I have been hesitant to add large binary assets lately because any small change in the configured compression/resize strategy would result in a new set of binary blobs that won't diff with their old versions resulting in a .git database that could potentially grow quite large very quickly.  And once they're in, they're difficult to remove.  I could be convinced that this is not really a big deal.

**Comment by rgrp** [comment]
@danfowler @mchelen can you guys finalise this item and take a decision one way or the other.

**Comment by danfowler** [comment]
If it's OK with you and @mchelen I would move to close and follow @loleg's earlier [suggestion](https://github.com/okfn/okfn.github.com/pull/252#issuecomment-68185809) of moving this to a dedicated repo for pushing to a CDN (assets.okfn.org?) so we can get the benefit of the smaller file sizes without complicating this relatively small, straightforward repo.

**Comment by danfowler** [comment]
Due to GitHub's [forthcoming support for large files](https://git-lfs.github.com/), I feel much better about large files in the repo going forward.  I will be closing this PR and merging an updated version of it in the next few days.

**Pull request closed without merging**
