### PR TITLE
2015Q4 Newsletter

### PR DESCRIPTION
**Pull request by jwieder**
Please see this thread for additional information: https://github.com/okfn/okfn.github.com/issues/374

Also note @danfowler comments on commit #46b3311: https://github.com/jwieder/okfn.github.com/commit/46b3311bbae16049b4fab15e6ec34c2c81ae5770

We have yet to confirm if @davbre would like to be listed as Advisory Group Member or would prefer another title, so we may want to wait to process this pull request until we know for sure. [UPDATE: @davbre confirmed his title so this should be G2G]

Finally, I apologize for the large number of commits for adding a single file. I made a stupid mistake embedding the images into the newsletter; failing to realize that spaces in front of the image markup rendered the image embed as code instead of as an image.

### CODE REVIEW

**Comment by jwieder** [comment]
Thanks @davbre !

**Comment by danfowler** [comment]
Love it! :100: :100: :100: :100: :100: :100:

**Comment by danfowler** [comment]
@jwieder Excellent work.  Merged.  Can I ask you to post a link to the post on the Labs mailing list (https://lists.okfn.org/mailman/listinfo/okfn-labs) and also on the Discussion forum (https://discuss.okfn.org/c/open-knowledge-labs)?

**Comment by jwieder** [comment]
Hey @danfowler Thanks - I would be happy to take care of the newsletter on an ongoing basis as part of my contribution to OKFN if thats alright with everyone (I obv need to get around to submitting some useful code as well). I've added a link to the forum and I dont believe I was on the mailing list already so I am pending signup now. I sent a link email through but Im not sure it will make it until my account is live.

**Comment by danfowler** [comment]
That's excellent @jwieder, glad to have you :+1:

**Comment by danfowler** [comment]
@jwieder can you close all the issues related to this newsletter and create a new issue for the next newsletter (Q1 2016) like this one: https://github.com/okfn/okfn.github.com/issues/374 ?

**Comment by jwieder** [comment]
@danfowler np im on it.

**Pull request merged**
